### ISSUE TITLE
[Feature Request] Set manual modes to mirror tado settings

### ISSUE THREAD

**Issue by Cardo1** [lukasroegner/homebridge-tado#13]
Hello,

I’ve just started using this plugin, which is considerably better than tado’s own fairly terrible implementation.

However, there is one thing that the tado implementation does that it would be good if it were an option in this plugin.

When setting temperatures in HK, this is shown as a manual setting in tado.  In the tado app, you can set different behaviours for “Manual Control on tado Device” for each zone.  This is the setting that setting temperatures through tado HK use.  Options are “indefinitely”, “until next automatic change” and “timer”.

This plugin lets us set either “indefinitely”, which is the default, or “until next automatic change” under the options, but this applies to all zones.  In tado, I have some zones set to indefinitely, others to until next auto change, and others on a timer.  Would it be possible to have an option that will use tado’s manual settings for each zone?

Thanks.

**Comment by lukasroegner** [comment]
Hi @Cardo1,

Yes, it would be possible to move the global settings into device-specific settings. I'll gladly accept PRs for this feature!

**Comment by Cardo1** [comment]
Having had the wife (who’s the software engineer, not me!) have a look at the node-tado-client, it looks like the API doesn’t affect the zones in the same way the settings in the tado app do.

When set to auto, it uses the “until next automatic change” setting in tado.  It does not recognise the default behaviours set for each zone within the tado app.

Node-tado-client does however allow for setting auto, manual and a timer, which would mimic the tado settings.  I’ll see if the wife can implement per-zone options to allow for manual/auto/timer settings.

Manual = Until ended by user
Auto = Until next automatic change
Integer = Timer in seconds

(edit: corrected the way tado behaves under different modes)

**Comment by Cardo1** [comment]
I’m having a bit of a head scratching moment.  The Node-tado-client provides the following options for the termination point when setting a temperature:

auto
next_time_block
manual
integer

This plugin seems to use “auto” for the “switchToAutoInNextTimeBlock” option.  So what’s the difference between auto and next_time_block?

**Comment by Cardo1** [comment]
Having done some more digging around the API, it doesn’t look like we can read the “Manual Control on tado Device” settings, so looks like the only way to do this is to mirror the settings in the HB config.  The wife will have a look...

**Comment by Cardo1** [comment]
Got it working.

Dearest wife will sort out a PR tomorrow.

**Comment by Cardo1** [comment]
We’ve got the changes working so users can set auto/manual/timer for each zone, however we’re struggling with the updated config.schema.json.  It’s not the wife’s area of expertise and she’s struggling to get it to work when adding options to add individual zone config.

**Comment by lukasroegner** [comment]
You can submit the PR and I'll update the config.schema.json for you. Please make sure that the new config (individual zone configuration) is compatible with the old settings (global zone configuration).

**Comment by Cardo1** [comment]
The individual zone configs, if set, override the global configuration.  If nothing is set for an individual zone then it defaults to the global configuration.  I’ll ask the wife to do the PR.

**Comment by lukasroegner** [comment]
That sounds like a great solution! Looking forward to your PR!

**Comment by Cardo1** [comment]
I think we got there, in the end.  Looks like there were a few hiccups transferring the working files onto Github.  🤷‍♂️

**Comment by lukasroegner** [comment]
New version on master branch and NPM (0.5.0). I added the missing config.schema.json. Huge thank you to your wife for the PR!
