### ISSUE TITLE
[Feature Request] Sensors for solar intensity and air quality

### ISSUE THREAD

**Issue by adamrzanek** [lukasroegner/homebridge-tado#17]
Is it possible for you to add solar intensity features like in [This plugin](https://www.npmjs.com/package/homebridge-tado-platform) ? Or maybe even outside air quality if it is possibly. It’s a feature of tado app. I really want to switch to your plugin exclusively

**Comment by lukasroegner** [comment]
It's possible to implement those features. Feel free to submit a PR!

**Comment by adamrzanek** [comment]
@lukasroegner thanks! Don’t know how to submit a PR :)

**Comment by adamrzanek** [comment]
https://github.com/nitaybz/homebridge-tado-ac#readm

Hi, i don’t know how to do pull request... but i see another plugin with those features :) Can you implement it in your plugin? :)

**Comment by adamrzanek** [comment]
https://github.com/mattdavis90/node-tado-client i can see that there’s somehting like air comfort there. And i have one more feature request - temperature sensors

**Comment by lukasroegner** [comment]
Closed in favor of #31.
