### ISSUE TITLE
Automatic-Modus isn't working, when using Apple HomeKit Automation

### ISSUE THREAD

**Issue by wegi95** [lukasroegner/homebridge-tado#18]
The mode "automatic" is only working, when I change the temperature in HomeKit.
However, when I select the automatic mode as part of a HomeKit automation-shortcut, it changes the temperature like it does in the manual mode.

Maybe this is a bug of iOS 14, but since I haven't tried it at iOS 13, I cannot say for sure.

![IMG_4991](https://user-images.githubusercontent.com/62469253/94599197-66500b00-0290-11eb-9f82-cec380d8648b.PNG)
Result when using the "automatic" mode in HomeKit.
![IMG_4992](https://user-images.githubusercontent.com/62469253/94599203-67813800-0290-11eb-87a8-e9dfecffbe8b.PNG)
Result when using the "automatic" mode as part of a HomeKit automation.
![IMG_4993](https://user-images.githubusercontent.com/62469253/94599206-694afb80-0290-11eb-8da7-0525af1f3881.PNG)
"Automatic" mode in HomeKit.

**Comment by lukasroegner** [comment]
I assume that you created the automation within the Apple Home app? Check the automation in a third-party HomeKit app, the Apple Home app often adds unwanted settings to an automation (due to the poor interface).

**Comment by wegi95** [comment]
Thank you. When creating the automation in a third-party app and saving it as a scene, it is working perfectly with the shortcut section at HomeKit automation.
