### ISSUE TITLE
API & Zones

### ISSUE THREAD

**Issue by Lorccan** [lukasroegner/homebridge-tado#19]
On homebridge startup, 4 heating Zones are created:

```
[10/3/2020, 17:23:07] [TadoPlatform] Create heating zone with ID 2 and name Dining Room.
[10/3/2020, 17:23:07] [TadoPlatform] Create heating zone with ID 4 and name Bedroom.
[10/3/2020, 17:23:07] [TadoPlatform] Create heating zone with ID 5 and name Guest Bathroom.
[10/3/2020, 17:23:07] [TadoPlatform] Create heating zone with ID 6 and name Bathroom.
```

I am having two issues with the API:

1. When I GET a zone's value using its name (e.g. Bedroom) via the API, I see 'Zone not found' in the homebridge log (and nothing is returned:
```
REQUEST:
{
  "method": "GET",
  "transformRequest": [
    null
  ],
  "transformResponse": [
    null
  ],
  "url": "http://10.0.1.210:40810/zones/Bedroom",
  "headers": {
    "Authorization": "xxxxxx",
    "Accept": "application/json, text/plain, */*"
  },
  "data": "{\n\"target-state\": \"auto\"\n}",
  "timeout": {}
}

RESPONSE:
400 - Bad Request
```
  However, if I provide the ID (e.g. 4), I do get the expected JSON returned with `target-state` and `target-temperature`:
```
REQUEST:
{
  "method": "GET",
  "transformRequest": [
    null
  ],
  "transformResponse": [
    null
  ],
  "url": "http://10.0.1.210:40810/zones/4",
  "headers": {
    "Authorization": "xxxxxx",
    "Accept": "application/json, text/plain, */*"
  },
  "data": "{\n\"target-state\": \"auto\"\n}",
  "timeout": {}
}

RESPONSE:
{
  "target-state": "auto",
  "target-temperature": 22
}
```

2. When I POST to change a zone's value, I have the same problem, with slight variations.
- Posting using the Zone ID gets  `"status": 200`in the header, but nothing in the response body. The value does NOT change on the server.
- Posting using the Zone name gets `"status": 400` - i.e. Bad Response - but nothing in the response body.

I can provide any further information that you need. Please ask.

**Comment by lukasroegner** [comment]
You are right, the docs for the API were not correct. I updated it so that is now says "ZONE-ID" instead of "ZONE-NAME".
Setting the target state via POST should however work if you provide the ID instead of the name.

**Comment by Lorccan** [comment]
Thanks.

What should the POST response body contain?

**Comment by lukasroegner** [comment]
The response for POST should be 200 without body

**Comment by Lorccan** [comment]
Thank you.

I don't know what I was doing wrong yesterday, but I confirm all is now working for me as expected with the POST (using Zone ID)

I'll close this now.
