### ISSUE TITLE
Question: tado v1 supported?

### ISSUE THREAD

**Issue by beatpaul** [lukasroegner/homebridge-tado#2]
Hi!
Is the first tado version v1 (no native HomeKit support) suppoted?

Thx

**Comment by lukasroegner** [comment]
Hi @beatpaul,

Actually, I cannot tell you. This plugin uses the web API of Tado. I assume that, as long as you can control your system with the Web UI, it will work.

**Comment by beatpaul** [comment]
Just tried it --> works perfekt so far :)

except one  thing: config ui-x probably mixes up your plugin with this one 

[(https://www.npmjs.com/package/homebridge-tado)]

and wants to update due to the same name ... 
is there a work-around ?

thx

**Comment by lukasroegner** [comment]
Hi @beatpaul, I don't think that there is a workaround. I haven't published this plugin on NPM as there are a ton of plugins doing nearly the same, they work for 99% of all use cases. I implemented this plugin to get this specific accessories configuration (Thermostat + window sensor in one accessory) exposed in HomeKit with a fire-and-forget mechanism for communication with the API.
