### ISSUE TITLE
[Feature Request] Add option to hide specific devices

### ISSUE THREAD

**Issue by boomcreativemartin** [lukasroegner/homebridge-tado#20]
Hi, 

I would like to have the functionality to only show the hot water switch as i find automations often fail with using homebridge to set states on the central heating. 

Ideally there would be a line in the JSON variables to have hide-device = True / False 

Is this something you can impliment

**Comment by NeilJonesOnline** [comment]
Came on here to ask the same.  I'd like to stick with the native HomeKit support for my Tado° system, except that doesn't expose the HW controls to Home/Siri, so was hoping I might be able to use this plug-in just for that (and exclude my other 15 Tado° devices!)

**Comment by mpjalexander** [comment]
This feature gets a vote from me too. The Tado Platform plugin supports this capability, so it would be something else that would allow me to switch to this plugin.

**Comment by lukasroegner** [comment]
Closed in favor of #31.
