### ISSUE TITLE
dependency problems

### ISSUE THREAD

**Issue by bnSonic** [lukasroegner/homebridge-tado#22]
when i install this plugin i get this list of Warnings - anything i can do or will this plugin get an update for that?
(Installed on HomeBridge - Docker - on a Synology)

npm WARN deprecated simple-oauth2@2.5.2: simple-oauth2 v2 is no longer supported. Please upgrade to v3 for further support
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated wreck@14.2.0: This module has moved and is now available at @hapi/wreck. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated bourne@1.1.2: This module has moved and is now available at @hapi/bourne. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated boom@7.3.0: This module has moved and is now available at @hapi/boom. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.

**Comment by bnSonic** [comment]
here are details from Homebridge Home-Panel if that helps

Homebridge: v1.2.3
OS	Alpine Linux (3.12.1)
Node.js Version	v14.15.0
Npm Version	v6.14.8
Docker	Yes
Service-Modus	Yes

**Comment by lukasroegner** [comment]
I'm not planning to update the dependencies in the near future. The plugin will work even if those warning occur.

**Comment by WinfriedO** [comment]
again depedency problem. axios creating vulnerability. What about maintenance here?
