### ISSUE TITLE
Homekit overrides Tado

### ISSUE THREAD

**Issue by JarFiles** [lukasroegner/homebridge-tado#27]
### Description:
Setting a manual timer on tado and opening the homekit app causes the created time to be overridden.

### Steps to reproduce:
- Open the tado app and change the temperature
- Set the expiry to a time (e.g. 30 minutes)
- Open the homekit app and select the device

### Expected behaviour:
- homekit should display the new state: HEATING and the set temperature from the tado app
- timer should be preserved

### Current behaviour:
- Opening the homekit app causes the timer in the tado app to get overridden by the current homekit state
- e.g. if you set the temperature to 15°C in the tado app and the expiry to 30 mins and the homekit app's last state is still auto, the device will switch back to auto mode instead of displaying HEATING - 15°C

**Comment by lukasroegner** [comment]
Indeed, this is a severe bug in the Apple HomeKit app (confirmed on iOS 14.3). Whenever you open the details view of a thermostat device, the current state (OFF, HEAT, AUTO) is used to set the target state.

There is no workaround that I could implement (as these requests to set the target state cannot be distinguished from real user input). Please provide feedback to Apple.
