### ISSUE TITLE
Auto-assist controls customization

### ISSUE THREAD

**Issue by flareman** [lukasroegner/homebridge-tado#29]
First off, thanks for all the great work.

On the the issue at hand, auto-assist features such as home/away and open window functionality report automatically only when the user has an active subscription. For those of us who don't have the subscription, the user has to actually tap the notification and go into the tado app to change home/away mode, likewise for open window mode.

It would be nice to not have to see the open window and occupancy sensors in HomeKit. You could change the accessories you register, depending on whether the user has set the "isAutoAssistEnabled" flag in config.json: if it is false, all you have to do is register a switch for home/away functionality and that's about it.

Thanks again.

**Comment by lukasroegner** [comment]
You can already hide the occupancy sensors, just set `areOccupancySensorsEnabled` and `isGlobalHomeAwayEnabled` to `false`. Starting with version 0.7.0, you can also disable all window sensors by setting `areWindowSensorsHidden` to `true`.

**Comment by flareman** [comment]
Thanks, I'll check it ASAP and get back to you. I do want the home/away switch available, though, as it enables me to replicate the auto-assist home/away functionality - will it work on its own?

**Comment by flareman** [comment]
A quick follow up: as stated before, I want the home/away switch available, but not the occupancy sensor (which does nothing without auto-assist), neither the open window sensor. I set areOccupancySensorsEnabled to false, isGlobalHomeAwayEnabled to true, and areWindowSensorsHidden to true. Nothing changed: I still see both the occupancy sensor and the open window sensor, both in Homebridge and Home.app.

Is this a bug, or intended plugin behavior? I'm attaching some screenshots for clarification:

<img width="311" alt="Στιγμιότυπο 2021-01-22, 12 23 06 πμ" src="https://user-images.githubusercontent.com/621631/105420219-a7599a00-5c48-11eb-85a8-c9df88a1938b.png">
<img width="1205" alt="Στιγμιότυπο 2021-01-22, 12 24 06 πμ" src="https://user-images.githubusercontent.com/621631/105420224-a9235d80-5c48-11eb-94cb-42cadb905401.png">

UPDATE: after updating to the latest version of the plugin (namely 0.7.0), the open window sensor has indeed disappeared. The occupancy sensor remains present, however, with the settings described above. From what I understand, for users who don't have auto-assist, the occupancy sensor reflects the state of the global home/away switch. That was my initial issue report about; should I open a new issue on this?
