### ISSUE TITLE
Occupancy sensors

### ISSUE THREAD

**Issue by Kohle81** [lukasroegner/homebridge-tado#3]
Hi Lukas,

I became aware of your tado plugin via smartapfel.de.  I would like to switch to your plugin, my current plugin still shows the presence of the registered people.  Is it possible to include these sensors?  Greetings Manuel

**Comment by lukasroegner** [comment]
Hi @Kohle81, it is possible to add occupancy sensors for each geo-fence enabled mobile device.

**Comment by Kohle81** [comment]
That would be great 👍

**Comment by lukasroegner** [comment]
@Kohle81 Occupancy sensors are now supported by the plugin, please try it out.

**Comment by Kohle81** [comment]
wow, that was quick.  I will test and report as soon as possible

**Comment by Kohle81** [comment]
Installation was ok and occupancy sensors switches are generated. Tomorrow I will try to test geofencing. Thanks for your work!

I want to spent you a coffee, but there's no button

**Comment by Kohle81** [comment]
I have tested it a few days. It works perfect 👌
