### ISSUE TITLE
Publish to npm possible?

### ISSUE THREAD

**Issue by martinnock** [lukasroegner/homebridge-tado#5]
Hi,

I am using homebridge via HOOBS and do not manage to install the plugin via the terminal.
Is it possible to publish via npm?

Thanks!

**Comment by lukasroegner** [comment]
@martinnock Does Hoobs already support scoped NPM packages?

**Comment by martinnock** [comment]
@lukasroegner Thanks for looking into this.
The [HOOBS Support page](https://hoobs.org/knowledge-base/how-plugins-work-with-hoobs-advanced/) says it allows for scoped packages.

I hope this is of any help ... thanks

**Comment by lukasroegner** [comment]
@martinnock I renamed the plugin, it is now published on NPM as `homebridge-tado-smart-thermostat`.
