### ISSUE TITLE
Improve display of current heating mode

### ISSUE THREAD

**Issue by benno666** [lukasroegner/homebridge-tado#7]
Hey,

it looks like your plugin determines the current heating mode by checking the target temperature against the actual indoor temperature. As long as the target temperature isn‘t reached, it‘s assumed that the thermostat is heating, and if it‘s warm enough inside, the thermostat should be off. This works in most cases, but since I had some problems from time to time with Tado, there should be a better approach. Could you use the heatingPower.percentage value instead? If it‘s greater than 0, the thermostat is definitely heating, else it is off.

Best regards,
Benno

**Comment by lukasroegner** [comment]
Makes sense, I changed it in the latest version 0.3.2!
