### ISSUE TITLE
Scenes do not set AUTO mode properly

### ISSUE THREAD

**Issue by bxlouis** [lukasroegner/homebridge-tado#9]
Hi Lukas,

While performing some testing, I think I discovered a bug when dealing with scenes in the Home app.

I am using an "At home" scene, in which I am setting all the thermostats to "AUTO" mode, so that they resume heating and follow the schedule set in the Tado app.

While it works well if I select AUTO manually from each thermostat, it does not work correctly when the same action is performed from a scene. It seems that in this case, the temperature displayed in the Home App is also sent which sets the thermostat to HEAT mode, with the aforementioned temperature. 

Note that it is not possible not to select a temperature when creating the scene.
Could you take a look at this?

**Comment by bxlouis** [comment]
Also, playing with scenes, I get random log messages 
`[5/10/2020, 12:04:42 PM] [TadoPlatform] 5 - Failed to switch target state to HEATING
[5/10/2020, 12:04:42 PM] [TadoPlatform] 3 - Failed to switch target state to HEATING
[5/10/2020, 12:04:42 PM] [TadoPlatform] 1 - Failed to set target temperature to 18
[5/10/2020, 12:04:42 PM] [TadoPlatform] 2 - Failed to switch target state to HEATING`

I don't know why it happens. It happens when I switch from a scene to another with the Home app.

**Comment by lukasroegner** [comment]
@bxlouis Use a third-party HomeKit app to create the scenes (e.g. Controller for HomeKit, Eve, Home+). Those apps allow you to specify the exact properties that should be set.
